// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iwanjunaid/basesvc/usecase/author/repository (interfaces: AuthorSQLRepository,AuthorDocumentRepository,AuthorCacheRepository,AuthorEventRepository,AuthorGravatarRepository,AuthorGravatarCacheRepository)

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	model "github.com/iwanjunaid/basesvc/domain/model"
	reflect "reflect"
)

// MockAuthorSQLRepository is a mock of AuthorSQLRepository interface
type MockAuthorSQLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorSQLRepositoryMockRecorder
}

// MockAuthorSQLRepositoryMockRecorder is the mock recorder for MockAuthorSQLRepository
type MockAuthorSQLRepositoryMockRecorder struct {
	mock *MockAuthorSQLRepository
}

// NewMockAuthorSQLRepository creates a new mock instance
func NewMockAuthorSQLRepository(ctrl *gomock.Controller) *MockAuthorSQLRepository {
	mock := &MockAuthorSQLRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorSQLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorSQLRepository) EXPECT() *MockAuthorSQLRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockAuthorSQLRepository) Create(arg0 context.Context, arg1 *model.Author) (*model.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockAuthorSQLRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorSQLRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method
func (m *MockAuthorSQLRepository) Find(arg0 context.Context, arg1 string) (*model.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*model.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockAuthorSQLRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAuthorSQLRepository)(nil).Find), arg0, arg1)
}

// FindAll mocks base method
func (m *MockAuthorSQLRepository) FindAll(arg0 context.Context) ([]*model.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]*model.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockAuthorSQLRepositoryMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAuthorSQLRepository)(nil).FindAll), arg0)
}

// MockAuthorDocumentRepository is a mock of AuthorDocumentRepository interface
type MockAuthorDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorDocumentRepositoryMockRecorder
}

// MockAuthorDocumentRepositoryMockRecorder is the mock recorder for MockAuthorDocumentRepository
type MockAuthorDocumentRepositoryMockRecorder struct {
	mock *MockAuthorDocumentRepository
}

// NewMockAuthorDocumentRepository creates a new mock instance
func NewMockAuthorDocumentRepository(ctrl *gomock.Controller) *MockAuthorDocumentRepository {
	mock := &MockAuthorDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorDocumentRepository) EXPECT() *MockAuthorDocumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockAuthorDocumentRepository) Create(arg0 context.Context, arg1 *model.Author) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockAuthorDocumentRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorDocumentRepository)(nil).Create), arg0, arg1)
}

// FindAll mocks base method
func (m *MockAuthorDocumentRepository) FindAll(arg0 context.Context) ([]*model.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]*model.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockAuthorDocumentRepositoryMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAuthorDocumentRepository)(nil).FindAll), arg0)
}

// MockAuthorCacheRepository is a mock of AuthorCacheRepository interface
type MockAuthorCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorCacheRepositoryMockRecorder
}

// MockAuthorCacheRepositoryMockRecorder is the mock recorder for MockAuthorCacheRepository
type MockAuthorCacheRepositoryMockRecorder struct {
	mock *MockAuthorCacheRepository
}

// NewMockAuthorCacheRepository creates a new mock instance
func NewMockAuthorCacheRepository(ctrl *gomock.Controller) *MockAuthorCacheRepository {
	mock := &MockAuthorCacheRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorCacheRepository) EXPECT() *MockAuthorCacheRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockAuthorCacheRepository) Create(arg0 context.Context, arg1 string, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockAuthorCacheRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorCacheRepository)(nil).Create), arg0, arg1, arg2)
}

// Find mocks base method
func (m *MockAuthorCacheRepository) Find(arg0 context.Context, arg1 string) (*model.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*model.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockAuthorCacheRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAuthorCacheRepository)(nil).Find), arg0, arg1)
}

// FindAll mocks base method
func (m *MockAuthorCacheRepository) FindAll(arg0 context.Context, arg1 string) ([]*model.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1)
	ret0, _ := ret[0].([]*model.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockAuthorCacheRepositoryMockRecorder) FindAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAuthorCacheRepository)(nil).FindAll), arg0, arg1)
}

// MockAuthorEventRepository is a mock of AuthorEventRepository interface
type MockAuthorEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorEventRepositoryMockRecorder
}

// MockAuthorEventRepositoryMockRecorder is the mock recorder for MockAuthorEventRepository
type MockAuthorEventRepositoryMockRecorder struct {
	mock *MockAuthorEventRepository
}

// NewMockAuthorEventRepository creates a new mock instance
func NewMockAuthorEventRepository(ctrl *gomock.Controller) *MockAuthorEventRepository {
	mock := &MockAuthorEventRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorEventRepository) EXPECT() *MockAuthorEventRepositoryMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockAuthorEventRepository) Publish(arg0 context.Context, arg1, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockAuthorEventRepositoryMockRecorder) Publish(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAuthorEventRepository)(nil).Publish), arg0, arg1, arg2)
}

// MockAuthorGravatarRepository is a mock of AuthorGravatarRepository interface
type MockAuthorGravatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorGravatarRepositoryMockRecorder
}

// MockAuthorGravatarRepositoryMockRecorder is the mock recorder for MockAuthorGravatarRepository
type MockAuthorGravatarRepositoryMockRecorder struct {
	mock *MockAuthorGravatarRepository
}

// NewMockAuthorGravatarRepository creates a new mock instance
func NewMockAuthorGravatarRepository(ctrl *gomock.Controller) *MockAuthorGravatarRepository {
	mock := &MockAuthorGravatarRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorGravatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorGravatarRepository) EXPECT() *MockAuthorGravatarRepositoryMockRecorder {
	return m.recorder
}

// AvatarURL mocks base method
func (m *MockAuthorGravatarRepository) AvatarURL() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarURL")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AvatarURL indicates an expected call of AvatarURL
func (mr *MockAuthorGravatarRepositoryMockRecorder) AvatarURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarURL", reflect.TypeOf((*MockAuthorGravatarRepository)(nil).AvatarURL))
}

// GetProfile mocks base method
func (m *MockAuthorGravatarRepository) GetProfile() (*model.GravatarProfiles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile")
	ret0, _ := ret[0].(*model.GravatarProfiles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile
func (mr *MockAuthorGravatarRepositoryMockRecorder) GetProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockAuthorGravatarRepository)(nil).GetProfile))
}

// JSONURL mocks base method
func (m *MockAuthorGravatarRepository) JSONURL() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSONURL")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JSONURL indicates an expected call of JSONURL
func (mr *MockAuthorGravatarRepositoryMockRecorder) JSONURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSONURL", reflect.TypeOf((*MockAuthorGravatarRepository)(nil).JSONURL))
}

// URL mocks base method
func (m *MockAuthorGravatarRepository) URL() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URL indicates an expected call of URL
func (mr *MockAuthorGravatarRepositoryMockRecorder) URL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockAuthorGravatarRepository)(nil).URL))
}

// MockAuthorGravatarCacheRepository is a mock of AuthorGravatarCacheRepository interface
type MockAuthorGravatarCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorGravatarCacheRepositoryMockRecorder
}

// MockAuthorGravatarCacheRepositoryMockRecorder is the mock recorder for MockAuthorGravatarCacheRepository
type MockAuthorGravatarCacheRepositoryMockRecorder struct {
	mock *MockAuthorGravatarCacheRepository
}

// NewMockAuthorGravatarCacheRepository creates a new mock instance
func NewMockAuthorGravatarCacheRepository(ctrl *gomock.Controller) *MockAuthorGravatarCacheRepository {
	mock := &MockAuthorGravatarCacheRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorGravatarCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorGravatarCacheRepository) EXPECT() *MockAuthorGravatarCacheRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockAuthorGravatarCacheRepository) Create(arg0 context.Context, arg1 string, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockAuthorGravatarCacheRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorGravatarCacheRepository)(nil).Create), arg0, arg1, arg2)
}

// Find mocks base method
func (m *MockAuthorGravatarCacheRepository) Find(arg0 context.Context, arg1 string) (*model.GravatarProfiles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*model.GravatarProfiles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockAuthorGravatarCacheRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAuthorGravatarCacheRepository)(nil).Find), arg0, arg1)
}
